smash> smash> smash> smash> smash> timeout_sample_file1.txt
timeout_sample_file2.txt
smash> before
smash> smash: got an alarm
after
smash> 0
end: 2
smash> smash: got an alarm
after
smash> 0
2
smash: got an alarm
smash: timeout 3 ../my_sleep 4 timed out!
smash> smash: got ctrl-C
smash> smash> [1] timeout 3 ../my_sleep 4 & : 2 X secs
smash> 0
2
smash: got an alarm
smash: timeout 3 ../my_sleep 4 & timed out!
smash: got ctrl-C
smash> smash> smash: got an alarm
smash: timeout 5 sleep 10 & timed out!
smash: got an alarm
smash: timeout 5 sleep 20 timed out!
smash> smash> smash: got an alarm
smash: timeout 3 sleep 30 timed out!
smash> smash: got an alarm
smash: timeout 7 sleep 15& timed out!
smash: got ctrl-C
smash> 0
smash> smash: got ctrl-Z
smash> 2
4
smash: got an alarm
smash: timeout 5 ../my_sleep 20& timed out!
smash> smash> 0
timeout 5 ../my_sleep 20& : 3
2
smash: got ctrl-Z
smash: process 3 was stopped
smash> timeout 5 ../my_sleep 20& : 3
smash> 4
smash: got an alarm
smash: timeout 5 ../my_sleep 20& timed out!
smash> smash> 0
timeout 5 ../my_sleep 20& : 4
2
smash: got ctrl-C
smash: process 4 was killed
smash> smash> smash: got an alarm
smash> smash> smash> smash> [1] timeout 5 sleep 100& : 5 X secs
[2] timeout 4 sleep 200& : 6 X secs
[3] timeout 2 sleep 300& : 7 X secs
[4] timeout 7 sleep 400& : 8 X secs
smash> smash: got an alarm
smash: timeout 2 sleep 300& timed out!
smash: got an alarm
smash: timeout 4 sleep 200& timed out!
smash: got an alarm
smash: timeout 5 sleep 100& timed out!
smash: got an alarm
smash: timeout 7 sleep 400& timed out!
smash> smash> smash: got an alarm
smash: timeout 2 sleep 4& timed out!
smash: got ctrl-C
smash: process 9 was killed
smash> smash> smash: got an alarm
smash: got ctrl-C
smash: process 10 was killed
smash> smash: sending SIGKILL signal to 0 jobs:
